builds:
  - binary: mackerel-plugin-postqueue
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/sugy/mackerel-plugin-postqueue/lib.version={{.Version}}
      - -X github.com/sugy/mackerel-plugin-postqueue/lib.commit={{.ShortCommit}}
      - -X github.com/sugy/mackerel-plugin-postqueue/lib.date={{.Date}}
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: sugy
    name: mackerel-plugin-postqueue
