builds:
  - binary: mackerel-plugin-postqueue
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: sugy
    name: mackerel-plugin-postqueue
